/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.38
 * Generated at: 2024-12-09 05:25:03 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Passport_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>Xworkz</title>\r\n");
      out.write("    <!-- Add Bootstrap CSS -->\r\n");
      out.write("    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css\" rel=\"stylesheet\" integrity=\"sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH\" crossorigin=\"anonymous\">\r\n");
      out.write("\r\n");
      out.write("    <style>\r\n");
      out.write("\r\n");
      out.write("    body {\r\n");
      out.write("             background-image: url('https://img.freepik.com/free-photo/3d-travel-icon-with-airplane_23-2151037375.jpg?semt=ais_hybrid');\r\n");
      out.write("            background-size: cover;\r\n");
      out.write("            background-position: center;\r\n");
      out.write("            background-repeat: no-repeat;\r\n");
      out.write("            min-height: 100vh;\r\n");
      out.write("            display: flex;\r\n");
      out.write("            flex-direction: column;\r\n");
      out.write("            justify-content: center;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("\r\n");
      out.write("     }\r\n");
      out.write("        </style>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<div class=\"container mt-5\">\r\n");
      out.write("    <h1 class=\"mb-4\">Passport Form</h1>\r\n");
      out.write("    <form action=\"passport\" method=\"post\">\r\n");
      out.write("        <!-- Passport Office -->\r\n");
      out.write("        <div class=\"mb-3\">\r\n");
      out.write("            <label for=\"passportOffice\" class=\"form-label\">Passport Office</label>\r\n");
      out.write("            <select id=\"passportOffice\" name=\"passportOffice\" class=\"form-select\" required>\r\n");
      out.write("                <option>-- Select --</option>\r\n");
      out.write("                <option>KARNATAKA</option>\r\n");
      out.write("                <option>AP</option>\r\n");
      out.write("                <option>TN</option>\r\n");
      out.write("                <option>UP</option>\r\n");
      out.write("                <option>MH</option>\r\n");
      out.write("            </select>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <!-- Given Name -->\r\n");
      out.write("        <div class=\"mb-3\">\r\n");
      out.write("            <label for=\"givenName\" class=\"form-label\">Given Name</label>\r\n");
      out.write("            <input type=\"text\" id=\"givenName\" name=\"givenName\" class=\"form-control\" required>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <!-- Surname -->\r\n");
      out.write("        <div class=\"mb-3\">\r\n");
      out.write("            <label for=\"surname\" class=\"form-label\">Surname</label>\r\n");
      out.write("            <input type=\"text\" id=\"surname\" name=\"surname\" class=\"form-control\" required>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <!-- Date of Birth -->\r\n");
      out.write("        <div class=\"mb-3\">\r\n");
      out.write("            <label for=\"dob\" class=\"form-label\">Date of Birth</label>\r\n");
      out.write("            <input type=\"text\" id=\"dob\" name=\"dob\" class=\"form-control\" required>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <!-- Email -->\r\n");
      out.write("        <div class=\"mb-3\">\r\n");
      out.write("            <label for=\"email\" class=\"form-label\">Email</label>\r\n");
      out.write("            <input type=\"email\" id=\"email\" name=\"email\" class=\"form-control\" required>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <!-- Do you want your Login ID to be the same as E-mail ID? -->\r\n");
      out.write("        <div class=\"mb-3\">\r\n");
      out.write("            <label class=\"form-label\">Do you want your Login ID to be the same as E-mail ID?</label><br>\r\n");
      out.write("            <div class=\"form-check form-check-inline\">\r\n");
      out.write("                <input type=\"radio\" id=\"loginYes\" name=\"loginSameAsEmail\" value=\"Yes\" class=\"form-check-input\" required>\r\n");
      out.write("                <label for=\"loginYes\" class=\"form-check-label\">Yes</label>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"form-check form-check-inline\">\r\n");
      out.write("                <input type=\"radio\" id=\"loginNo\" name=\"loginSameAsEmail\" value=\"No\" class=\"form-check-input\">\r\n");
      out.write("                <label for=\"loginNo\" class=\"form-check-label\">No</label>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <!-- Login ID -->\r\n");
      out.write("        <div class=\"mb-3\">\r\n");
      out.write("            <label for=\"loginId\" class=\"form-label\">Login ID</label>\r\n");
      out.write("            <input type=\"text\" id=\"loginId\" name=\"loginId\" class=\"form-control\" required>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <!-- Password -->\r\n");
      out.write("        <div class=\"mb-3\">\r\n");
      out.write("            <label for=\"password\" class=\"form-label\">Password</label>\r\n");
      out.write("            <input type=\"password\" id=\"password\" name=\"password\" class=\"form-control\" required>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <!-- Confirm Password -->\r\n");
      out.write("        <div class=\"mb-3\">\r\n");
      out.write("            <label for=\"confirmPassword\" class=\"form-label\">Confirm Password</label>\r\n");
      out.write("            <input type=\"password\" id=\"confirmPassword\" name=\"confirmPassword\" class=\"form-control\" required>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <!-- Hint Question -->\r\n");
      out.write("        <div class=\"mb-3\">\r\n");
      out.write("            <label for=\"hintQuestion\" class=\"form-label\">Hint Question</label>\r\n");
      out.write("            <select id=\"hintQuestion\" name=\"hintQuestion\" class=\"form-select\" required>\r\n");
      out.write("                <option>-- Select --</option>\r\n");
      out.write("                <option>your pet name?</option>\r\n");
      out.write("                <option>your school name?</option>\r\n");
      out.write("                <option>your childhood best friend name?</option>\r\n");
      out.write("            </select>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <!-- Hint Answer -->\r\n");
      out.write("        <div class=\"mb-3\">\r\n");
      out.write("            <label for=\"hintAnswer\" class=\"form-label\">Hint Answer</label>\r\n");
      out.write("            <input type=\"text\" id=\"hintAnswer\" name=\"hintAnswer\" class=\"form-control\" required>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <!-- Submit Button -->\r\n");
      out.write("        <button type=\"submit\" class=\"btn btn-primary\">Submit</button>\r\n");
      out.write("    </form>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<!-- Bootstrap JS and dependencies -->\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js\" integrity=\"sha384-GLhlTQ8iRABzRiV1TtiEohPNXknb0T9kq5rcLE70b2wW9S9E1M6g3ERF9bB4x9v6F\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
